In [146]:
import Pkg.instantiate
instantiate()
using BenchmarkTools: @ballocated
using Random: randperm
using LinearAlgebra
using CairoMakie

In [97]:
A = float([2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8])
b = float([2;2;2;2])
display(A)
display(b)
x_ref = A\b
display(x_ref)

n = size(A, 1)
for j=1:n
    for k=1:j-1
        for i=k+1:n
            A[i, j] -= A[i, k] * A[k, j]
        end
    end

    for i = j+1:n
        A[i, j] /= A[j, j]
    end
end

display(A)

4×4 Matrix{Float64}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

4-element Vector{Float64}:
 2.0
 2.0
 2.0
 2.0

4-element Vector{Float64}:
  2.9999999999999987
 -1.9999999999999984
 -1.9999999999999998
  1.9999999999999993

4×4 Matrix{Float64}:
 2.0  1.0  1.0  0.0
 2.0  1.0  1.0  1.0
 4.0  3.0  2.0  2.0
 3.0  4.0  1.0  2.0

In [107]:
n = length(b)
x = float([2;2;2;2])
display(A)
# Solve Ly=b
for i=1:n
    for j = i-1:-1:1
        x[i] -= A[i,j] * x[j]
    end
end

#Solve Ux=y
for i=n:-1:1
    for j = i+1:n
        x[i] -= A[i,j] * x[j]
    end
    x[i] /= A[i, i]
end

display(x)
# for k=1:n
#     for i=k+1:n
#         A[i, k] /= A[k,k]
#     end
#     for j=k+1:n, i=k+1:n
#         A[i,j] -= A[i,k] * A[k,j]
#     end
# end


4×4 Matrix{Float64}:
 2.0  1.0  1.0  0.0
 2.0  1.0  1.0  1.0
 4.0  3.0  2.0  2.0
 3.0  4.0  1.0  2.0

4-element Vector{Float64}:
  3.0
 -2.0
 -2.0
  2.0

In [46]:
for j=5:-1:1
    print(j)
end

54321

In [10]:
A = float([2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8])
display(A)

L , U, p = lu(A)

display(L)
display(U)
display(p)

n = size(A, 1)
P = collect(1 : n)
for k=1:n
    imx = k-1+argmax(abs.(A[k:end,k]))
    for j=1:n
        A[k,j],A[imx,j] = A[imx, j],A[k,j]
    end
    P[[k,imx]] = P[[imx,k]]

    for i=k+1:n
        A[i,k] /= A[k,k]
    end

    for j=k+1:n,i=k+1:n
        A[i,j] -= A[i,k]*A[k,j]
    end
end
display(P)
display(A)

4×4 Matrix{Float64}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

4×4 Matrix{Float64}:
 1.0    0.0       0.0       0.0
 0.75   1.0       0.0       0.0
 0.5   -0.285714  1.0       0.0
 0.25  -0.428571  0.333333  1.0

4×4 Matrix{Float64}:
 8.0  7.0    9.0        5.0
 0.0  1.75   2.25       4.25
 0.0  0.0   -0.857143  -0.285714
 0.0  0.0    0.0        0.666667

4-element Vector{Int64}:
 3
 4
 2
 1

4-element Vector{Int64}:
 3
 4
 2
 1

4×4 Matrix{Float64}:
 8.0    7.0        9.0        5.0
 0.75   1.75       2.25       4.25
 0.5   -0.285714  -0.857143  -0.285714
 0.25  -0.428571   0.333333   0.666667

In [255]:
function substitution!(x, LU, P = 1 : size(x, 1)) 
    # YOUR CODE HERE
    n = length(x)
    permute!(x, P)

    # Solve Ly=b
    for i=1:n
        for j = i-1:-1:1
            x[i] -= LU[i,j] * x[j]
        end
    end

    #Solve Ux=y
    for i=n:-1:1
        for j = i+1:n
            x[i] -= LU[i,j] * x[j]
        end
        x[i] /= LU[i, i]
    end
end

#----------------------------------------
# Problem b
#----------------------------------------
# This function takes in a matrix A and modifies
# it in place, such that is contains the stricly
# lower triangular part of L together with the
# upper triangular part of U.
function unpivoted_LU!(A)
    # YOUR CODE HERE
    n = size(A, 1)
    for j=1:n
        for k=1:j-1
            for i=k+1:n
                A[i, j] -= A[i, k] * A[k, j]
            end
        end

        for i = j+1:n
            A[i, j] /= A[j, j]
        end
    end
end

function pivoted_LU!(A)
    # The array that will be used to keep track of the permutation
    P = collect(1 : size(A, 1))
    # YOUR CODE HERE
    # returns the array representing the permutation
    n = size(A, 1)
    for k=1:n
        imx = k-1+argmax(abs.(A[k:end,k]))
        for j=1:n
            A[k,j],A[imx,j] = A[imx, j],A[k,j]
        end
        P[[k,imx]] = P[[imx,k]]

        for i=k+1:n
            A[i,k] /= A[k,k]
        end

        for j=k+1:n,i=k+1:n
            A[i,j] -= A[i,k]*A[k,j]
        end
    end
    return P
end

pivoted_LU! (generic function with 1 method)

In [218]:
size_list = 2 .^ (2 : 10)
error = Float64[]
growth_factor = Float64[]

function inf_norm(X)
    return maximum(sum(X, dims=2))
end

for m = size_list
    A = randn(m, m)
    b = randn(m)
    ref_norm = inf_norm(A)
    reference_x = A \ b
    unpivoted_LU!(A) 
    substitution!(b, A)

    push!(error, norm(reference_x - b)/norm(b))
    push!(growth_factor, inf_norm(UpperTriangular(A))/ref_norm)
end

error_plot = scatter(size_list, error, axis=(yscale=log10, xscale=log2, xlabel="Matrix Size, m", ylabel="Relative Error"))
save("relative_error.pdf", error_plot)

growth_factor_plot = scatter(size_list, growth_factor, axis=(yscale=log10, xscale=log2, xlabel="Matrix Size, m", ylabel="Growth Factor"))
save("growth_factor.pdf", growth_factor_plot)

CairoMakie.Screen{PDF}


In [203]:
A = float([2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8])
unpivoted_LU!(A)

function inf_norm(X)
    return maximum(sum(X, dims=2))
end
# sum_A = zeros(size(A, 1), 1) #(1:size(A, 1))
# print(sum_A)
# for i
sum_list = sum(A, dims=2)
println(sum_list)
println(maximum(sum(A, dims=2)))
println(inf_norm(UpperTriangular(A)))
display(A)


4×4 Matrix{Float64}:
 2.0  1.0  1.0  0.0
 2.0  1.0  1.0  1.0
 4.0  3.0  2.0  2.0
 3.0  4.0  1.0  2.0

[4.0; 5.0; 11.0; 10.0;;]
11.0
4.0


In [219]:
A = float([2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8])
display(A)

L , U, p = lu(A)

# display(L)
# display(U)
# display(p)

n = size(A, 1)
P = collect(1 : n)
for k=1:n
    imx = k-1+argmax(abs.(A[k:end,k]))
    for j=1:n
        A[k,j],A[imx,j] = A[imx, j],A[k,j]
    end
    P[[k,imx]] = P[[imx,k]]

    for i=k+1:n
        A[i,k] /= A[k,k]
    end

    for j=k+1:n,i=k+1:n
        A[i,j] -= A[i,k]*A[k,j]
    end
end
display(P)
display(A)

4×4 Matrix{Float64}:
 2.0  1.0  1.0  0.0
 4.0  3.0  3.0  1.0
 8.0  7.0  9.0  5.0
 6.0  7.0  9.0  8.0

4×4 Matrix{Float64}:
 1.0    0.0       0.0       0.0
 0.75   1.0       0.0       0.0
 0.5   -0.285714  1.0       0.0
 0.25  -0.428571  0.333333  1.0

4×4 Matrix{Float64}:
 8.0  7.0    9.0        5.0
 0.0  1.75   2.25       4.25
 0.0  0.0   -0.857143  -0.285714
 0.0  0.0    0.0        0.666667

4-element Vector{Int64}:
 3
 4
 2
 1

4-element Vector{Int64}:
 3
 4
 2
 1

4×4 Matrix{Float64}:
 8.0    7.0        9.0        5.0
 0.75   1.75       2.25       4.25
 0.5   -0.285714  -0.857143  -0.285714
 0.25  -0.428571   0.333333   0.666667

In [249]:
A = float([2 1 1 0; 4 3 3 1; 8 7 9 5; 6 7 9 8])
x = float([1;2;3;4])
display(A\x)

L , U, p = lu(A)

# display(L)
# display(U)
# display(p)

n = size(A, 1)
P = collect(1 : n)
for k=1:n
    imx = k-1+argmax(abs.(A[k:end,k]))
    for j=1:n
        A[k,j],A[imx,j] = A[imx, j],A[k,j]
    end
    P[[k,imx]] = P[[imx,k]]

    for i=k+1:n
        A[i,k] /= A[k,k]
    end

    for j=k+1:n,i=k+1:n
        A[i,j] -= A[i,k]*A[k,j]
    end
end
# display(P)
# display(A)

# n = length(b)
# x = float([2;4;6;8])

# for i=1:n
#     P[i] = x[P[i]]
# end
# x=float(P)
x = x[P]
display(x)
display(A)
# Solve Ly=b
for i=1:n
    for j = i-1:-1:1
        x[i] -= A[i,j] * x[j]
    end
end

#Solve Ux=y
for i=n:-1:1
    for j = i+1:n
        x[i] -= A[i,j] * x[j]
    end
    x[i] /= A[i, i]
end

display(x)

4-element Vector{Float64}:
  0.9999999999999993
  0.5000000000000008
 -1.4999999999999998
  0.9999999999999997

4-element Vector{Float64}:
 3.0
 4.0
 2.0
 1.0

4×4 Matrix{Float64}:
 8.0    7.0        9.0        5.0
 0.75   1.75       2.25       4.25
 0.5   -0.285714  -0.857143  -0.285714
 0.25  -0.428571   0.333333   0.666667

4-element Vector{Float64}:
  0.9999999999999991
  0.500000000000001
 -1.4999999999999998
  0.9999999999999997

In [281]:
function growth_matrix(m)
    # YOUR CODE GOES HERE
    A = zeros(m, m)
    for i=1:m
        A[i, i] = 1
        A[i, m] = 1
        for j=1:i-1
            A[i, j] = -1
        end
    end
    return(A)
end

growth_matrix (generic function with 1 method)

In [282]:
A = growth_matrix(5)
size_list = 2 .^ (2 : 10) 
growth_factor_pivot = Float64[]
error_pivot = Float64[]

function inf_norm(X)
    return maximum(sum(X, dims=2))
end

for m = size_list
    A = growth_matrix(m)
    b = randn(m)
    ref_norm = inf_norm(A)
    reference_x = A \ b
    P = pivoted_LU!(A) 
    substitution!(b, A, P)

    push!(error_pivot, norm(A*reference_x - b)/norm(b))
    push!(growth_factor_pivot, inf_norm(UpperTriangular(A))/ref_norm)
end

error_plot = scatter(size_list, error_pivot, axis=(yscale=log10, xscale=log2, xlabel="Matrix Size, m", ylabel="Relative Error"))
save("relative_error_pivot.pdf", error_plot)

# growth_factor_plot = scatter(size_list, growth_factor_pivot, axis=(yscale=log10, xscale=log2, xlabel="Matrix Size, m", ylabel="Growth Factor"))
# save("growth_factor_pivot.pdf", growth_factor_plot)

5×5 Matrix{Float64}:
  1.0   0.0   0.0   0.0  1.0
 -1.0   1.0   0.0   0.0  1.0
 -1.0  -1.0   1.0   0.0  1.0
 -1.0  -1.0  -1.0   1.0  1.0
 -1.0  -1.0  -1.0  -1.0  1.0

In [279]:
size_list = 2 .^ (2 : 10) 
growth_factor_pivot = Float64[]
error_pivot = Float64[]

function inf_norm(X)
    return maximum(sum(X, dims=2))
end

for m = size_list
    A = (randn(m, m) + 100 * I)[randperm(m), :]
    b = randn(m)
    ref_norm = inf_norm(A)
    reference_x = A \ b
    P = pivoted_LU!(A) 
    substitution!(b, A, P)

    push!(error_pivot, norm(reference_x - b)/norm(b))
    push!(growth_factor_pivot, inf_norm(UpperTriangular(A))/ref_norm)
end

error_plot = scatter(size_list, error_pivot, axis=(yscale=log10, xscale=log2, xlabel="Matrix Size, m", ylabel="Relative Error"))
save("relative_error_pivot.pdf", error_plot)

growth_factor_plot = scatter(size_list, growth_factor_pivot, axis=(yscale=log10, xscale=log2, xlabel="Matrix Size, m", ylabel="Growth Factor"))
save("growth_factor_pivot.pdf", growth_factor_plot)

CairoMakie.Screen{PDF}
