In [89]:
A = [
    1 2 3 4
    5 6 7 8
    9 10 11 12
]
v = [2, 4, 6, 8]

A*v

3-element Vector{Int64}:
  60
 140
 220

In [90]:
u = zeros(size(A)[1], 1)

for row in 1:size(A)[1]
    u[row] = 0
    for col in 1:size(A)[2]
        u[row] += A[row, col] * v[col]
    end
end
u

3×1 Matrix{Float64}:
  60.0
 140.0
 220.0

In [99]:
# u = zeros(size(A)[1], 1)

for col in 1:size(A)[2]
    for row in 1:size(A)[1]
        if col == 1
            u[row] = A[row, col] * v[col]
        else
            u[row] += A[row, col] * v[col]
        end
    end
end
u

3×1 Matrix{Float64}:
  60.0
 140.0
 220.0

In [101]:
B = [
    1 2 3 4
    5 6 7 8
    9 10 11 12
]

C = [
    2 4
    6 8
    10 12
    14 16
]

B*C

3×2 Matrix{Int64}:
 100  120
 228  280
 356  440

In [102]:
A = zeros(size(B)[1], size(C)[2])

for row in 1:size(B)[1]
    for col in 1:size(C)[2]
        for idx in 1: size(B)[2]
            A[row, col] += B[row, idx] * C[idx, col]
        end
    end
end
A

3×2 Matrix{Float64}:
 100.0  120.0
 228.0  280.0
 356.0  440.0

In [108]:
# A = zeros(size(B)[1], size(C)[2])

for idx in 1: size(B)[2]
    for row in 1:size(B)[1]
        for col in 1:size(C)[2]
            if idx == 1
                A[row, col] = B[row, idx] * C[idx, col]
            else
                A[row, col] += B[row, idx] * C[idx, col]
            end
        end
    end
end

A

3×2 Matrix{Float64}:
 100.0  120.0
 228.0  280.0
 356.0  440.0

In [110]:
# A = zeros(size(B)[1], size(C)[2])

for row in 1:size(B)[1]
    for idx in 1: size(B)[2]
        for col in 1:size(C)[2]
            if idx == 1
                A[row, col] = B[row, idx] * C[idx, col]
            else
                A[row, col] += B[row, idx] * C[idx, col]
            end
        end
    end
end

A

3×2 Matrix{Float64}:
 100.0  120.0
 228.0  280.0
 356.0  440.0

In [ ]:
A = zeros(size(B)[1], size(C)[2])

for row in 1:size(B)[1]
    for idx in 1: size(B)[2]
        for col in 1:size(C)[2]
            A[row, col] += B[row, idx] * C[idx, col]
        end
    end
end

A